### PR TITLE
Test the libmamba solver in CI

### PR DESCRIPTION
**Pull request by agriyakhetarpal**
builds on top of #19 (~let's get that merged first~ edit: merged!)

#### Test harness

- Tests are now parametrised to run with both the classic and libmamba solvers. A `solvers:` field in the test spec YAML, combined with the pytest plugin filtering, allows selecting one solver for the test. I've kept this as plural because the rattler solver will follow (#29), and we can then write things like `[classic, libmamba]` if we want to skip it
- The input model now supports a `force_reinstall` flag
- We can now load and inject package dependency metadata from channel repodata
- Exception handling for the "unsatisfiable" kind of tests is a bit more compatible with both solvers

#### Test suite

- Test cases have been either split or duplicated to provide solver-specific variants such as `B024[a|b]` and `I008[a|b]` and the like

#### Workflow

- A matrix added for GHA to run both jobs in parallel
- "Aggregate" job added, because of the "Require branches to be up to date before merging" setting I suggested enabling

### CODE REVIEW

**Comment by agriyakhetarpal** [comment]
The `AttributeError: type object 'str' has no attribute '__members__'` failures have a fix in #16.

**Comment by agriyakhetarpal** [comment]
[Edit: marking this as resolved]

Notes from the last time (early last week) when I was exploring this PR:

The 11 failures can be divided into two categories.
- Category 1: this is a code "bug" of some sort in `install.py`. 6 tests fail because libmamba raises solver-specific exception subclasses that aren't handled correctly. We have `raises(UnsatisfiableError)`, but then `exc_info.type == UnsatisfiableError` is `False` and then we fail to `else: raise` on B005, B006, C003, C004
	* LibMambaUnsatisfiableError is _not_ caught for some reason. It is a subclass of `UnsatisfiableError` so it should be caught. (valid for I004)
	* `PackagesNotFoundError` is _not_ caught by `pytest.raises(ResolvePackageNotFound)`. This is valid for B007
- Category 2 (different solver outputs): these are some given tests where libmamba genuinely returns different packages for whatever reason: B002, B022, B024, I006, and I008.

**Comment by agriyakhetarpal** [comment]
I had a chat with @jaimergp about the potential churn in renaming the required job that I suggested adding, which is only required to add the "Require branches to be up to date before merging" setting. I've set that up in e5bb2b447df098d04d0609d759468025132cad38.

File: pytest_conda_solvers/base_tests/install.py [hunk 1]
```diff
@@ -100,6 +104,16 @@ def add_base_url(base_url, arch, dist_strs):
...
+# TODO: maybe we should have this in __init__.py instead
+@lru_cache(maxsize=None)
+def _load_channel_package_index(channel_name, subdir):
+    """Load package metadata from channel repodata JSON files."""
+    source = "noarch" if subdir == "noarch" else "non-noarch"
+    try:
+        return load_data_file(Path(f"{channel_name}_{source}.json"))
+    except (FileNotFoundError, OSError):
+        return {}
+
```
Comment (jezdez) [inline pytest_conda_solvers/base_tests/install.py]: This duplicates the loading logic already in `data/__init__.py`'s `get_channel_repodata()` — same path construction, same `load_data_file` call, and a second `lru_cache` holding the same data in memory.

Consider delegating instead:

```suggestion
from ..data import get_channel_repodata


def _load_channel_package_index(channel_name, subdir):
    """Load package metadata from channel repodata JSON files."""
    try:
        repodata = get_channel_repodata(channel_name, subdir, "repodata.json")
        return repodata["packages"]
    except (FileNotFoundError, OSError):
        return {}
```

This keeps the loading path centralized and avoids caching the same JSON twice (once here and once in `get_channel_repodata`).

File: pytest_conda_solvers/base_tests/install.py [hunk 2]
```diff
@@ -304,17 +329,28 @@ def test_unsatisfiable(self, env, tmpdir, solver_backend, test, channel_server):
...
+                    assert set(unsatisfiable) == set(error_info["entries"])
+            case ResolvePackageNotFound() as exc:
+                if error_info.get("entries"):
+                    assert set((exc.bad_deps,)) == set(error_info["entries"])
+            case PackagesNotFoundError():
+                pass  # libmamba raises this instead of ResolvePackageNotFound; no entries check
+            case SpecsConfigurationConflictError() as exc:
+                kwargs = exc._kwargs
+                assert set(kwargs["requested_specs"]) == set(error_info["requested_specs"])
+                assert set(kwargs["pinned_specs"]) == set(error_info["pinned_specs"])
```
Comment (jezdez) [inline pytest_conda_solvers/base_tests/install.py:381]: Several of these cases now pass without verifying anything about the error content:

- `PackagesNotFoundError` → `pass` (no assertions)
- `UnsatisfiableError` → assertions conditional on both `error_info.get("entries")` and `isinstance(unsatisfiable, ...)`
- `ResolvePackageNotFound` → assertions conditional on `error_info.get("entries")`

Understandable for initial libmamba compatibility, but a test can now "pass" simply by raising the right exception class. Worth a TODO so this doesn't silently mask future regressions:

```suggestion
        match exc_info.value:
            case UnsatisfiableError() as exc:
                unsatisfiable = getattr(exc, "unsatisfiable", None)
                # TODO: tighten these checks as solver error reporting matures
                if error_info.get("entries") and isinstance(unsatisfiable, (set, frozenset)):
                    assert set(unsatisfiable) == set(error_info["entries"])
            case ResolvePackageNotFound() as exc:
                if error_info.get("entries"):
                    assert set((exc.bad_deps,)) == set(error_info["entries"])
            case PackagesNotFoundError():
                pass  # libmamba raises this instead of ResolvePackageNotFound; no entries check
            case SpecsConfigurationConflictError() as exc:
                kwargs = exc._kwargs
                assert set(kwargs["requested_specs"]) == set(error_info["requested_specs"])
                assert set(kwargs["pinned_specs"]) == set(error_info["pinned_specs"])
```

File: pytest_conda_solvers/base_tests/install.py (hunk 1 above)
Comment (agriyakhetarpal) [reply pytest_conda_solvers/base_tests/install.py]: Good catch, I missed it! Thanks!

File: pytest_conda_solvers/base_tests/install.py (hunk 2 above)
Comment (agriyakhetarpal) [reply pytest_conda_solvers/base_tests/install.py:381]: Thanks! I'm making some more changes here because I actually want to ensure this is right for the libmamba solver at least – I'd rather be more lenient and leave TODOs with the rattler solver (in #34) than with an established one. I'll mark it as draft for a slight bit.

**Comment by agriyakhetarpal** [comment]
Notes for myself as I work through this:

- `UnsatisfiableError`: there seems to be a bug where the old code checks `isinstance(unsatisfiable, (set, frozenset))` but the classic solver sets `.unsatisfiable` as a list, so the assertion is silently skipped even for classic.
- for libmamba (`LibMambaUnsatisfiableError` skips `UnsatisfiableError.__init__`, so `.unsatisfiable` doesn't exist): verifies the first/last of each chain package names of each conflict chain appear in the error message, so intermediaries like `nose` seem to be missing? I haven't come across this one
- `ResolvePackageNotFound`: this exception is only raised by the classic solver, which always has entries.

File: .github/workflows/tests.yml [hunk 3]
```diff
@@ -30,4 +37,14 @@ jobs:
...
+        env:
+          MATRIX_SOLVER: ${{ matrix.solver }}
+
+  pass:
+    name: Aggregate
+    needs: [test]
+    runs-on: ubuntu-slim
+    steps:
+      - name: Confirm all tests passed
+        run: echo "All tests passed successfully!"
```
Comment (jezdez) [inline .github/workflows/tests.yml]: As-is this job doesn't actually enforce anything: without an `if:`, it defaults to `success()`, so if any matrix job fails or is cancelled the Aggregate job is **skipped**. GitHub Actions reports skipped required checks as "Success" to branch protection, which means a broken matrix could merge with a green Aggregate. ([Known footgun](https://github.com/orgs/community/discussions/26822).)

Conda's own workflow uses [`re-actors/alls-green`](https://github.com/conda/conda/blob/main/.github/workflows/tests.yml#L780-L793) for exactly this — let's mirror that pattern (same pinned SHA conda uses):

```suggestion
  analyze:
    name: Aggregate
    needs: [test]
    if: '!cancelled()'
    runs-on: ubuntu-latest
    steps:
      - name: Determine Success
        uses: re-actors/alls-green@05ac9388f0aebcb5727afa17fcccfecd6f8ec5fe # v1.2.2
        with:
          jobs: ${{ toJSON(needs) }}
```

Notes:
- `if: '!cancelled()'` rather than `if: always()` — runs on matrix failure/skip but skips on workflow cancellation, which avoids spurious red checks on cancelled runs (matches conda).
- Dropped `ubuntu-slim` for `ubuntu-latest` since slim runner availability depends on org plan/settings; happy to flip back if it's confirmed available here.
- No `allowed-skips` — conda needs that for their `changes` filter; we don't have one, and any skip here should be a real failure.
- The job name "Aggregate" stays the same, so the branch-protection required-check name is unchanged.

Comment (agriyakhetarpal) [reply .github/workflows/tests.yml]: Thanks for these @jezdez – is there any way we can do away with `re-actors/alls-green` in your suggestion? I was intentionally trying to limit the number of external actions we have running on this repository, but I am also okay with this action if there is no good option otherwise 🙌🏻

(FTR, I tried to base this off https://github.com/scikit-hep/vector/blob/f53f07328e58ae1aa2ade21a738db7915daa6085/.github/workflows/ci.yml#L100-L104, but I would understand if it may not be enough and we should align on what we use in conda/conda)

Also, looks like the slim runner is available for everyone in public preview, BTW: https://github.blog/changelog/2025-10-28-1-vcpu-linux-runner-now-available-in-github-actions-in-public-preview/. We should be good!

**Comment by agriyakhetarpal** [comment]
Hmm, it looks like the newer libmamba solver is breaking our repodata server for some reason. I need the newer version, because I bumped the minimum conda version just now. I need it to access `.packages`, which I added in https://github.com/conda/conda/pull/15653, and that landed as part of 26.3.x. I'll bisect for a bit.

Side note: as part of the provenance updates, we should think of what the maximum difference in history between the conda revision and the conda version should be (no action here).

File: .github/workflows/tests.yml (hunk 3 above)
Comment (jezdez) [reply .github/workflows/tests.yml]: > is there any way we can do away with `re-actors/alls-green` in your suggestion?

Fair instinct on minimizing external actions, but I'd keep it here. The action is small, single-purpose, no network access, pinned to a SHA, [actively maintained](https://github.com/re-actors/alls-green/blob/release/v1/CHANGELOG.md), and already in the conda org's trust boundary ([`conda/conda`](https://github.com/conda/conda/blob/main/.github/workflows/tests.yml#L780-L793) uses it for the exact same purpose). The inline-shell alternative is a few lines of `contains(needs.*.result, ...)` that you have to remember to update if you add new result states to handle — same class of silent-footgun as the original `pass` job.

> (FTR, I tried to base this off scikit-hep/vector...)

Worth noting that vector's pattern is the same broken one — no `if:`, just `echo "All jobs passed"`. A failed matrix there → job skipped → branch protection sees "Success" → red CI can merge. Their workflow is pretty linear (single platform, no merge queue, no aggregated required check), so the bug hasn't bitten them. We're a different shape: multi-OS × multi-solver matrix, rattler incoming as a third axis, all aggregated into one required check. "No action" and "no enforcement" are different goals; vector's pattern conflates them.

> Also, looks like the slim runner is available for everyone in public preview

Nice, thanks for the link. Let's keep `ubuntu-slim` then.

Comment (agriyakhetarpal) [reply .github/workflows/tests.yml]: Thanks for the extra context! Let's keep the action in that case and I think I'll raise this with scikit-hep separately at some point.

**Comment by agriyakhetarpal** [comment]
Ready for another look, @jezdez (and @jaimergp, if you have time)!

File: pytest_conda_solvers/base_tests/install.py [hunk 4]
```diff
@@ -1,6 +1,8 @@
 import re
 import sys
 from contextlib import contextmanager, nullcontext
+from functools import lru_cache
+from pathlib import Path
```
Comment (jezdez) [inline pytest_conda_solvers/base_tests/install.py]: Both of these are now unused — `_load_channel_package_index` no longer uses `@lru_cache` (since `get_channel_repodata` is already cached) and there's no `Path(...)` construction anywhere. Safe to drop:

```suggestion
```

**Review by jezdez — COMMENTED** [review]
Another pass — the workflow refactor and error handling came out really nicely. The per-solver matching with explanatory comments in `test_unsatisfiable` is a big improvement over the earlier "lenient pass" version, and the alls-green Aggregate job is exactly what we discussed.

A few small cleanup items in `install.py` around imports, plus a couple of optional FYIs below. Nothing blocking — happy to approve once the import cleanup is in.

File: pytest_conda_solvers/base_tests/install.py [hunk 5]
```diff
@@ -20,6 +23,7 @@
 from conda.plugins.virtual_packages import cuda
 from conda.resolve import MatchSpec
 
+from ..data import load_data_file
```
Comment (jezdez) [inline pytest_conda_solvers/base_tests/install.py]: `load_data_file` is no longer used in this module — the only data import we need now is `get_channel_repodata` (currently imported mid-file at line 107). Let's hoist it up here and drop the misplaced import below:

```suggestion
from ..data import get_channel_repodata
```

File: pytest_conda_solvers/base_tests/install.py [hunk 6]
```diff
@@ -100,6 +104,16 @@ def add_base_url(base_url, arch, dist_strs):
         f"{base_url}/{dist_str.replace('${{ arch }}', arch)}" for dist_str in dist_strs
     )
 
+from ..data import get_channel_repodata
```
Comment (jezdez) [inline pytest_conda_solvers/base_tests/install.py]: If you apply the suggestion above (hoist `get_channel_repodata` to the top imports), this line and the blank below can go. Also worth adding a blank line between `_load_channel_package_index` and `package_record_from_dist_str` for PEP 8.

File: pytest_conda_solvers/server.py [hunk 7]
```diff
@@ -66,9 +66,13 @@ async def conda_format_repo_contents(full_path: str):
     async def repodata(
         channel_name: str,
         subdir: str,
-        filename: RepodataFilename,
+        filename: str,
     ):
-        return get_channel_repodata(channel_name, subdir, filename.value)
+        try:
+            validated = RepodataFilename(filename)
```
Comment (jezdez) [inline pytest_conda_solvers/server.py:78]: (Optional) Worth a one-line comment here explaining _why_ we manually validate to 404 rather than letting FastAPI auto-422 on the enum: I'm guessing libmamba probes for repodata filenames we don't serve and treats 404 as "not present" but 422 as a hard error? The commit message hints at this but a code comment would help future readers.

File: pixi.toml [hunk 8]
```diff
@@ -1,5 +1,6 @@
 [dependencies]
-conda = "*"
+conda = ">=26.3.0"
+conda-libmamba-solver = ">=26.4.0"
```
Comment (jezdez) [inline pixi.toml:3]: (FYI, not blocking) Adding `conda-libmamba-solver` to the top-level `[dependencies]` means it gets installed for the classic-solver test runs too. That's harmless functionally, but if you want a tighter setup later, this could move into a pixi feature/group used only by `test-libmamba-solver`. Fine to defer until/unless rattler joins and we want to avoid bloating every env.

**Review by jezdez — APPROVED** [review]
No blockers left, only minor nice-to-haves

File: pytest_conda_solvers/base_tests/install.py (hunk 4 above)
Comment (agriyakhetarpal) [reply pytest_conda_solvers/base_tests/install.py]: Thanks! I'll follow this up with banning unused imports; it looks like we can do a lot of linting cleanup.

File: pytest_conda_solvers/server.py (hunk 7 above)
Comment (agriyakhetarpal) [reply pytest_conda_solvers/server.py:78]: Right, yes, my commit message was just a rough idea and it isn't very helpful, thanks for pointing that out! There are two things here, and I'd say both conda and conda-libmamba-solver (maybe are involved. Here's some context, which I'm writing here because I think we can have some follow-ups here:

- CLS's `_repodata_shards` calls `response.raise_for_status()` on 422
- conda's `conda_http_errors` catches the `HTTPError` and raises `CondaHTTPError`
- `CondaHTTPError.__init__` does `message = body.get("detail") or message` (based on RFC 9457 in the comment above it)
- However, FastAPI's 422 body has `"detail"` as a list (as per its validation error schema). Which is why `dals(...) + message` leads to the `TypeError: can only concatenate str (not "list") to str` that we end up seeing.

So the bug is in `conda.exceptions.CondaHTTPError`, as it's not handling non-string `detail` values. I'll put together a PR in conda/conda for that!

That said, could the CLS shards code be more resilient? Like, a 422 from a server that doesn't support shards should be treated like a 404 as a graceful fallback, not propagated? (I'm not sure about this one, since I haven't investigated that codebase too much yet)

File: pixi.toml (hunk 8 above)
Comment (agriyakhetarpal) [reply pixi.toml:3]: Neat, I was wanting to use such a feature! Yes, I think I would like to do this. I will indeed avoid it here and will put it in the rattler solver PR, or maybe another smaller PR to keep it scoped.

File: pytest_conda_solvers/server.py (hunk 7 above)
Comment (agriyakhetarpal) [reply pytest_conda_solvers/server.py:78]: I added a comment in 894e28d2dfcf3ef3abb867b7ba012d10c9d93d2f, but I'll leave this conversation unresolved due to my CLS question above. Thanks!
